### ISSUE TITLE
Missing "Create new group" button

### ISSUE THREAD

**Issue by fleaz** [OpenSplit/opensplit-frontend#3]
Because of the new DB layout I wiped the database for the development installation. But now I can't create a group and therefore can't test any of the features :D

**Comment by emsuiko** [comment]
@f-breidenstein, please document the API call to create a group! :(

**Comment by fleaz** [comment]
Oh wow, this is indeed missing from the api docs :/ 

Will fix the docs ASAP before doing anything else with the backend!

Creating a new group is done via a POST to `/groups`
with `{"name": "myfancygroupname"}` in the body.

**Comment by fleaz** [comment]
This was fixed in 4870ac2f2edafa0767e183dd28e644422ecd8905
